PUT  http://localhost:8080/events/2
content-Type: application/json

{
    "name": "updated test event",
    "description": "A test event",
    "location": "Test location (Updated!)",
    "dateTime": "2024-08-08T15:30:00Z"
}
